const state_mapping = {
  الجزائر: 16,
  باتنة: 5,
  البويرة: 10,
  غليزان: 40,
  "عين تموشنت": 31,
  "برج بوعريريج": 34,
  النعامة: 45,
  تيارت: 14,
  عنابة: 23,
  ورقلة: 30,
  سطيف: 19,
  قسنطينة: 25,
  "عين الدفلى": 44,
  المسيلة: 28,
  وهران: 31,
  تيبازة: 42,
  البليدة: 9,
  بومرداس: 35,
  تلمسان: 13,
  ميلة: 43,
  األغواط: 3,
  "أم البواقي": 1,
  "سيدي بلعباس": 22,
  الوادي: 39,
  الجلفة: 17,
  غرداية: 47,
  سكيكدة: 21,
  قاملة: 4,
  املدية: 48,
  سعيدة: 20,
  معسكر: 29,
  تبسة: 12,
  املسيلة: 28,
  بسكرة: 7,
  البيض: 32,
  الطارف: 36,
  الشلف: 2,
  أدرار: 11,
  مستغانم: 27,
  خنشلة: 40,
  بجاية: 6,
  تمنراست: 11,
  تيسمسيلت: 38,
  "سوق أهراس": 41,
};

export const agencies = [
  {
    phone_number: "023917474",
    abbreviation: "نوي",
    agency_name: "نوي للسياحة و األسفار",
    state_name: "الجزائر",
    state_code: state_mapping["الجزائر"] || null,
  },
  {
    phone_number: "023440142",
    abbreviation: "طابا",
    agency_name: "طابا فواياج",
    state_name: "الجزائر",
    state_code: state_mapping["الجزائر"] || null,
  },
  {
    phone_number: "033271997",
    abbreviation: "العوالي",
    agency_name: "العوالي للسياحة و األسفار",
    state_name: "باتنة",
    state_code: state_mapping["باتنة"] || null,
  },
  {
    phone_number: "026720066",
    abbreviation: "النجاح",
    agency_name: "النجاح للسياحة واالسفار",
    state_name: "البويرة",
    state_code: state_mapping["البويرة"] || null,
  },
  {
    phone_number: "046787377",
    abbreviation: "المحسنون",
    agency_name: "المحسنون تور",
    state_name: "غليزان",
    state_code: state_mapping["غليزان"] || null,
  },
  {
    phone_number: "046723404",
    abbreviation: "المرينية",
    agency_name: "المرينية للخدمات السياحية",
    state_name: "غليزان",
    state_code: state_mapping["غليزان"] || null,
  },
  {
    phone_number: "043783874",
    abbreviation: "تموشنت",
    agency_name: "تموشنت سفر",
    state_name: "عين تموشنت",
    state_code: state_mapping["عين تموشنت"] || null,
  },
  {
    phone_number: "035734773",
    abbreviation: "انوار الصباح",
    agency_name: "وكالة انوار الصباح للسياحة و االسفار",
    state_name: "برج بوعريريج",
    state_code: state_mapping["برج بوعريريج"] || null,
  },
  {
    phone_number: "049575454",
    abbreviation: "زيدون",
    agency_name: "وكالة زيدون للسياحة و السفر",
    state_name: "النعامة",
    state_code: state_mapping["النعامة"] || null,
  },
  {
    phone_number: "05615954",
    abbreviation: "لجدار",
    agency_name: "لجدار ترافل اجنسي",
    state_name: "تيارت",
    state_code: state_mapping["تيارت"] || null,
  },
  {
    phone_number: "038407902",
    abbreviation: "راس الحمراء",
    agency_name: "راس الحمراء للسياحة",
    state_name: "عنابة",
    state_code: state_mapping["عنابة"] || null,
  },
  {
    phone_number: "029609564",
    abbreviation: "السعف الذهبي",
    agency_name: "السعف الذهبي",
    state_name: "ورقلة",
    state_code: state_mapping["ورقلة"] || null,
  },
  {
    phone_number: "036453278",
    abbreviation: "عيساوي",
    agency_name: "عيساوي للسياحة",
    state_name: "سطيف",
    state_code: state_mapping["سطيف"] || null,
  },
  {
    phone_number: "031871111",
    abbreviation: "نوبا",
    agency_name: "نوبا ترافل",
    state_name: "قسنطينة",
    state_code: state_mapping["قسنطينة"] || null,
  },
  {
    phone_number: "027504261",
    abbreviation: "دوي",
    agency_name: "دوي للسفر",
    state_name: "عين الدفلى",
    state_code: state_mapping["عين الدفلى"] || null,
  },
  {
    phone_number: "035349696",
    abbreviation: "بني طلحة",
    agency_name: "بني طلحة سياحة",
    state_name: "المسيلة",
    state_code: state_mapping["المسيلة"] || null,
  },
  {
    phone_number: "041239854",
    abbreviation: "بني طلحة",
    agency_name: "بني طلحة للسياحة و األسفار",
    state_name: "وهران",
    state_code: state_mapping["وهران"] || null,
  },
];
