export const ksa_cities = [
  { "code": "RUH", "name": "الرياض" },
  { "code": "JED", "name": "جدة" },
  { "code": "MEC", "name": "مكة المكرمة" },
  { "code": "MED", "name": "المدينة المنورة" },
  { "code": "DMM", "name": "الدمام" },
  { "code": "KBR", "name": "الخبر" },
  { "code": "HUF", "name": "الهفوف" },
  { "code": "TAF", "name": "الطائف" },
  { "code": "KHU", "name": "خميس مشيط" },
  { "code": "BUR", "name": "بريدة" },
  { "code": "UNA", "name": "عنيزة" },
  { "code": "YNB", "name": "ينبع" },
  { "code": "ABH", "name": "أبها" },
  { "code": "TUU", "name": "تبوك" },
  { "code": "HAQ", "name": "حائل" },
  { "code": "NJR", "name": "نجران" },
  { "code": "ARA", "name": "عرعر" },
  { "code": "QUR", "name": "القطيف" },
  { "code": "JUB", "name": "الجبيل" },
  { "code": "BHA", "name": "بيشة" }
];