export const APP_NAME = process.env.NEXT_PUBLIC_APP_NAME || "ميقات";
export const APP_DEFAULT_TITLE = "ميقات (تجريبي)";
export const APP_TITLE_TEMPLATE = `%s - ${APP_NAME}`;
export const APP_DESCRIPTION = `Generated by create ${APP_NAME}`;

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  APP_NAME,
  APP_DEFAULT_TITLE,
  APP_TITLE_TEMPLATE,
  APP_DESCRIPTION,
};
